name: Qt CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qt
      run: |
        choco install qt5-default
        dir C:\Qt
        dir "C:\Qt\5.15.2\"
        dir "C:\Qt\5.15.2\mingw81_64"
        dir "C:" /s | findstr /i "qmake.exe"
        dir "C:" /s | findstr /i "nmake.exe"

    - name: Add Qt to PATH
      run: echo "C:\Qt\5.15.2\mingw81_64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build Qt project
      run: |
        C:\Qt\5.15.2\mingw81_64\bin\qmake -project
        C:\Qt\5.15.2\mingw81_64\bin\qmake
        C:\Qt\5.15.2\mingw81_64\bin\nmake

    - name: Run Qt application
      run: .\qt-hello-world.exe
